{
  try {
    exitReasonQ.put(new Integer(reason));
  }
 catch (  InterruptedException e) {
    e.printStackTrace();
  }
}
