{
  mc.setDefaultResponseTimeout(200);
  mockSocket.close();
  replay(mockSocket);
  mockWriter.setSendResponse(false);
  try {
    mc.login();
    fail("No TimeoutException on login()");
  }
 catch (  AuthenticationFailedException e) {
    assertEquals("Unable to send challenge action",e.getMessage());
    assertEquals("Timeout waiting for response to Challenge",e.getCause().getMessage());
    assertTrue(e.getCause() instanceof TimeoutException);
  }
  assertEquals("createSocket not called 1 time",1,mc.createSocketCalls);
  assertEquals("createWriter not called 1 time",1,mc.createWriterCalls);
  assertEquals("createReader not called 1 time",1,mc.createReaderCalls);
  assertEquals("challenge action not sent 1 time",1,mockWriter.challengeActionsSent);
  assertEquals("unexpected login action sent",0,mockWriter.loginActionsSent);
  assertEquals("unexpected other actions sent",0,mockWriter.otherActionsSent);
  assertEquals("setSocket() not called 1 time",1,mockReader.setSocketCalls);
  Thread.sleep(10);
  assertEquals("run() not called 1 time",1,mockReader.runCalls);
  assertEquals("unexpected call to die()",0,mockReader.dieCalls);
  verify(mockSocket);
}
